-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versi server:                 10.4.20-MariaDB - mariadb.org binary distribution
-- OS Server:                    Win64
-- HeidiSQL Versi:               11.2.0.6213
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- membuang struktur untuk table arsa_blog.categories
CREATE TABLE IF NOT EXISTS `categories` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `categories_name_unique` (`name`),
  UNIQUE KEY `categories_slug_unique` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Membuang data untuk tabel arsa_blog.categories: ~3 rows (lebih kurang)
/*!40000 ALTER TABLE `categories` DISABLE KEYS */;
INSERT INTO `categories` (`id`, `name`, `slug`, `created_at`, `updated_at`) VALUES
	(1, 'Journalist', 'journalist', '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(2, 'Broadcaster', 'broadcaster', '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(3, 'Music Director', 'music-director', '2021-10-30 04:26:24', '2021-10-30 04:26:24');
/*!40000 ALTER TABLE `categories` ENABLE KEYS */;

-- membuang struktur untuk table arsa_blog.failed_jobs
CREATE TABLE IF NOT EXISTS `failed_jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Membuang data untuk tabel arsa_blog.failed_jobs: ~0 rows (lebih kurang)
/*!40000 ALTER TABLE `failed_jobs` DISABLE KEYS */;
/*!40000 ALTER TABLE `failed_jobs` ENABLE KEYS */;

-- membuang struktur untuk table arsa_blog.migrations
CREATE TABLE IF NOT EXISTS `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Membuang data untuk tabel arsa_blog.migrations: ~6 rows (lebih kurang)
/*!40000 ALTER TABLE `migrations` DISABLE KEYS */;
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
	(1, '2014_10_12_000000_create_users_table', 1),
	(2, '2014_10_12_100000_create_password_resets_table', 1),
	(3, '2019_08_19_000000_create_failed_jobs_table', 1),
	(4, '2019_12_14_000001_create_personal_access_tokens_table', 1),
	(5, '2021_08_25_154531_create_posts_table', 1),
	(6, '2021_08_26_040817_create_categories_table', 1);
/*!40000 ALTER TABLE `migrations` ENABLE KEYS */;

-- membuang struktur untuk table arsa_blog.password_resets
CREATE TABLE IF NOT EXISTS `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  KEY `password_resets_email_index` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Membuang data untuk tabel arsa_blog.password_resets: ~0 rows (lebih kurang)
/*!40000 ALTER TABLE `password_resets` DISABLE KEYS */;
/*!40000 ALTER TABLE `password_resets` ENABLE KEYS */;

-- membuang struktur untuk table arsa_blog.personal_access_tokens
CREATE TABLE IF NOT EXISTS `personal_access_tokens` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tokenable_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint(20) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Membuang data untuk tabel arsa_blog.personal_access_tokens: ~0 rows (lebih kurang)
/*!40000 ALTER TABLE `personal_access_tokens` DISABLE KEYS */;
/*!40000 ALTER TABLE `personal_access_tokens` ENABLE KEYS */;

-- membuang struktur untuk table arsa_blog.posts
CREATE TABLE IF NOT EXISTS `posts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `category_id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `excerpt` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `published_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `posts_slug_unique` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Membuang data untuk tabel arsa_blog.posts: ~23 rows (lebih kurang)
/*!40000 ALTER TABLE `posts` DISABLE KEYS */;
INSERT INTO `posts` (`id`, `category_id`, `user_id`, `title`, `slug`, `image`, `excerpt`, `body`, `published_at`, `created_at`, `updated_at`) VALUES
	(1, 3, 2, 'Sed corrupti asperiores unde dolor.', 'odit-ullam-consequuntur-minima-numquam-nesciunt', NULL, 'Laudantium minus voluptatem possimus ut commodi blanditiis quidem. Quia sit aperiam sed aut omnis provident iusto porro. Quos et quis eligendi voluptates.', '<p>Qui eius occaecati inventore enim totam distinctio veniam sint. Totam optio quis et tempora iusto cumque. Perspiciatis velit dolor rerum cumque et.</p><p>Cupiditate at tenetur non debitis id amet quis. Quidem qui voluptates ut dolores modi eos perspiciatis. Molestiae sint earum nesciunt culpa ut omnis non. Voluptatem ad rerum culpa porro perspiciatis voluptate.</p><p>Vel accusantium iusto culpa. Qui et nam quis repudiandae quasi vero. Inventore quia error exercitationem unde sequi enim.</p><p>Repudiandae fuga itaque deserunt voluptatibus non repellendus omnis. Quo perferendis sit soluta velit sed consequatur ipsa. Ab ducimus dolor aut dolorem earum modi illo. Ea et ipsa consequuntur dicta quis distinctio. Ut quia quaerat est autem aut laudantium dolore.</p><p>Exercitationem rerum nesciunt hic quidem. Et voluptatem quos illum magnam veniam. Id consequatur ut necessitatibus dignissimos et qui praesentium numquam. Illum qui nobis qui culpa amet ut. Aut voluptate expedita vel dolore cumque.</p><p>Veritatis at soluta eos nisi maxime autem veniam. Repellendus doloribus eveniet aut non. Cum minima et voluptatum nam architecto laborum. Non illum sequi ea ex ut.</p><p>Corrupti aut natus illum assumenda illum magni ullam culpa. Harum magnam officiis et sed amet quia quasi et. Ut deleniti ut id inventore in.</p><p>Qui non id qui magni vel labore ipsam soluta. Nostrum animi facere id eius non voluptas consequatur saepe. Quibusdam neque laboriosam autem voluptate. Beatae nam commodi repellendus enim mollitia voluptatem ut. Ab dolor beatae eius mollitia quia aut reprehenderit autem.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(2, 3, 3, 'Officiis dolore ut.', 'ab-sint-molestias-ullam-vero-a-est', NULL, 'Quam dicta nostrum repudiandae quia autem nobis impedit. Ipsa cupiditate et voluptates. Culpa similique quas accusantium rerum quia. Quia asperiores voluptatem nemo doloribus.', '<p>Explicabo animi temporibus voluptatem fugiat repudiandae. Eligendi earum velit perspiciatis sint et quis occaecati sunt. Et dolorem consequuntur eius nemo. Nihil voluptates sunt incidunt sed odio in sequi.</p><p>Consectetur sunt deleniti eos. Ipsa recusandae aut modi omnis autem laudantium. Qui laborum aliquam est provident porro.</p><p>Facere vel illo fuga aperiam exercitationem. Quae nobis dignissimos doloremque omnis officia id explicabo. Exercitationem facere est est excepturi quis. Consequatur omnis voluptas iusto aut reiciendis.</p><p>Corrupti assumenda voluptatem quidem quam consequatur officiis. Et aut consequatur iure velit esse voluptatem. Veniam corporis labore tempore quia. Aut aperiam natus perferendis eius qui ea quos. Sunt qui voluptatem dolor quia quam placeat assumenda et.</p><p>Voluptatibus accusamus laboriosam aliquid temporibus officiis dolores ut. Esse sunt expedita atque totam. Ea omnis quisquam sapiente accusamus. Omnis inventore eos libero reprehenderit eos commodi.</p><p>Qui enim rerum magni reprehenderit corporis ratione. Eius dolores nihil aut quis. Officiis eius sapiente quis nobis dicta aperiam fuga. Et placeat voluptas totam assumenda rerum et et.</p><p>Officia quis debitis at cum. Dolor blanditiis ut ea dolor non nam est. Alias quo rerum praesentium.</p><p>Saepe itaque et voluptatem amet repudiandae. Ut sit perferendis cupiditate modi eligendi cum at.</p><p>Corporis odio pariatur vitae necessitatibus et eum et. Vel rem laudantium tempora quaerat consequatur impedit.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(4, 2, 3, 'Et qui et quo distinctio eum assumenda eligendi molestiae error nesciunt.', 'voluptatibus-eos-dolorem-doloremque-est-hic', NULL, 'Eaque quidem illo voluptatum. Repudiandae qui non repellendus suscipit rem aut velit. Qui placeat doloribus sed autem ut.', '<p>Beatae voluptas perferendis magni voluptatem sapiente. Dolorum dolores dolores rem nobis libero consectetur. Repellendus corrupti labore minima. Omnis explicabo odit et velit.</p><p>Commodi rerum corrupti sit pariatur incidunt. Sed numquam aperiam quae labore atque dolorem amet. Illum quam incidunt est nobis. Quo maiores dolores omnis tenetur.</p><p>Laborum quod aut qui voluptas molestiae magni expedita. Qui et et possimus aut voluptatem ipsum. Totam sit voluptatum qui provident modi consequatur.</p><p>Ex quam et quae eum libero velit dolor aut. Dolores numquam incidunt ipsa nisi possimus eligendi aut pariatur. Animi consequuntur eum ut quaerat.</p><p>Non consequatur est voluptates enim. Voluptatibus ut minima voluptates impedit necessitatibus ad illum. Et vitae dolores cum consequuntur commodi reiciendis. Magni ut dolorem blanditiis impedit maxime et tenetur.</p><p>Et est quibusdam totam omnis. Sint autem vel assumenda laborum. Autem error laborum quia quam et suscipit fugiat. Hic sunt repellat et quis dolor eum ut.</p><p>Aperiam nemo id iure voluptatem. Non odit rerum natus modi vel ipsa.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(5, 2, 2, 'Reprehenderit tenetur et ipsam et nobis.', 'qui-minus-exercitationem-nisi-dolore-excepturi-odit', NULL, 'Repudiandae voluptatibus dolorem recusandae deserunt. Assumenda rerum numquam ut reiciendis provident. Natus autem nostrum voluptas mollitia maiores. Aut repellendus error illo praesentium repellendus. Aliquam itaque occaecati ut quidem.', '<p>Omnis aut exercitationem assumenda. Qui exercitationem labore velit odio doloremque.</p><p>Nihil aut tempore expedita. Molestiae culpa odio labore qui voluptatem voluptates quis quas. Qui eveniet doloribus quidem sit nisi aut.</p><p>Quidem placeat architecto laboriosam voluptatem placeat. Harum blanditiis eveniet ipsum deleniti error. Tempora fugit aliquid error ducimus corrupti sed vitae. Nulla cupiditate adipisci soluta adipisci ullam ab.</p><p>Eum ea maiores tempora sequi necessitatibus. Eius et ut doloremque a voluptatem.</p><p>Qui in magnam deleniti quos. Unde libero voluptate praesentium debitis cupiditate eos eius. Ex autem quas laudantium laudantium. Cumque cupiditate ut officiis eligendi.</p><p>Quo ad tempora natus quos modi omnis. Voluptatem labore enim amet et maiores. Et laboriosam tempore adipisci omnis. Adipisci ea quaerat repellat a voluptas culpa.</p><p>Sed nobis soluta praesentium et magni. Quia ea id corrupti dolore. Iusto omnis fugit assumenda.</p><p>Tempora molestiae est rerum iste ex atque ullam. Rerum sit exercitationem est laborum. Ex excepturi quia quas. Nostrum quae rerum non est sint.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(6, 2, 3, 'Laborum sint nihil qui quia eos omnis voluptas.', 'nostrum-in-dolor-quis-rem-dolorem-beatae', NULL, 'Autem dolor nulla tempore a nisi. Alias dolor vel enim consectetur. Quos quod quam quasi magnam aliquid. Nihil eligendi voluptas fugit suscipit sed est nesciunt.', '<p>Fuga saepe ea qui reprehenderit modi odit. Consequatur in nobis ipsa quod aut. Delectus optio distinctio aut consequatur ducimus ipsa.</p><p>Ut odit dolorem numquam ut. Dolor aut perspiciatis quis eius veniam. Et iusto quas cupiditate id est est.</p><p>Atque et voluptas quo aliquid possimus pariatur totam. Et sed magni voluptatum cupiditate placeat et.</p><p>Animi blanditiis ipsam nam nisi ipsum aut molestiae. Assumenda voluptas mollitia quidem tenetur sunt amet. Amet est voluptatem voluptates rerum ut saepe tempora.</p><p>Facere rem autem exercitationem qui. Cumque qui corrupti vel voluptatem incidunt est. In non repellat tenetur et.</p><p>Et sit ducimus debitis facere in doloremque. Est quo qui nostrum et sed sunt. Expedita id quibusdam fugit ducimus earum. Modi velit velit fugiat commodi quibusdam quidem.</p><p>Sequi qui ut vero officia voluptatem. Consequuntur enim culpa inventore aut ut. Placeat quo facere sit repellendus ut.</p><p>Ut consequatur debitis eligendi nam et a numquam. Eum et voluptatem mollitia reprehenderit quas laboriosam repudiandae. Nulla voluptas est modi qui impedit. Iusto eos quas ut provident officia nam quisquam.</p><p>Dolor vitae pariatur eum occaecati quam. Nihil tempora hic ipsa mollitia qui. Dolor consequatur minus ullam consequatur aspernatur deleniti dolorum repellat. Voluptatibus velit repellat molestiae est et ea.</p><p>Deserunt dolores perspiciatis dolor voluptas placeat. Quibusdam velit sed sequi voluptatibus est dolores. Nostrum sit eos minima facilis. Est aut deleniti est possimus eos rerum.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(7, 3, 2, 'Reprehenderit voluptas aut maxime commodi sunt.', 'non-a-ut-et-voluptatem-tempora-minima', NULL, 'Provident placeat unde quos excepturi. Incidunt rerum corrupti qui consequatur eum iste. Rerum quas dicta non et non quia.', '<p>Et voluptas consequuntur optio veniam. Quam minima voluptate ut beatae laborum. Odit totam fugiat iure expedita cupiditate. Ipsam nisi rerum ut voluptatibus molestias quo facilis.</p><p>Numquam excepturi corrupti aut quam quis eligendi. Eveniet modi magnam et explicabo. In deserunt placeat cumque veritatis dignissimos neque possimus provident.</p><p>Occaecati deserunt est omnis. Quia saepe sint et ab et velit. Esse cumque quia error doloribus.</p><p>Praesentium facilis cupiditate et error eos ut. Tempora nam necessitatibus beatae temporibus. Ratione nisi voluptatem et illum. Sed laboriosam tempora ea aliquam.</p><p>Et et quae consequatur minus optio temporibus aliquid necessitatibus. Eaque ut dolorem velit quis sed quidem inventore. Fuga sunt adipisci qui voluptatum placeat voluptas.</p><p>Expedita laborum minus et temporibus aliquam corporis suscipit. Facere nisi laudantium earum dolor totam saepe quis.</p><p>Voluptates optio esse expedita possimus. Corporis odio adipisci enim quos cupiditate. Quo et ut ut suscipit debitis aut.</p><p>Eum sunt amet eos perferendis. Nulla aperiam consequatur labore minus sit. Occaecati animi voluptates sit blanditiis veniam voluptatem. Id consequatur voluptatem quis sunt deserunt et. Itaque enim rerum qui ea placeat rem autem.</p><p>Aut consectetur natus quo porro consectetur. Libero et molestiae vel perferendis suscipit pariatur facere. Et est ipsam et autem aut odit. Explicabo quaerat quia hic veniam perferendis. Vel porro repellat tenetur rerum magnam odio.</p><p>Est quo asperiores maxime. Dolorum aut eum et quae consequatur maxime quia. Eum autem fuga aut quia doloremque fugit. Suscipit veniam fuga dolorem deleniti.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(8, 2, 2, 'Impedit et est voluptatem.', 'corporis-in-ullam-velit-mollitia-optio-veritatis', NULL, 'Odio dolore et quia. Ipsa dolorem qui modi. Ut et ut vero autem.', '<p>Temporibus dolor hic molestiae est quo voluptate. Corporis iste rerum facilis nesciunt laborum ipsam et. Et iste aut magnam fugit sit. Voluptatem voluptas et id exercitationem excepturi. Dicta quis voluptatem est sunt sint qui.</p><p>Id eius laborum culpa hic. Aut unde illum commodi qui aut aperiam nobis repellendus. Numquam quas eligendi ab. Occaecati rerum aut ut et molestias.</p><p>Nesciunt sed ipsum nihil porro non ea. Aperiam eaque cum error occaecati. Dolor nobis repellat corporis dolorem pariatur numquam quos dignissimos.</p><p>Aliquam occaecati nostrum est modi dolorem enim doloribus. Totam suscipit nisi delectus fugit quibusdam similique dicta. Quam natus fugit est rerum pariatur ad consequatur. Porro deleniti enim tempora distinctio.</p><p>Animi tenetur amet eligendi earum. Aut veritatis nesciunt repellat illo molestiae temporibus. Velit nisi dignissimos corrupti architecto perspiciatis. Qui optio aliquam fugit possimus saepe. Necessitatibus nobis consequatur enim asperiores et.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(9, 1, 2, 'Voluptatum porro earum voluptas nisi natus modi.', 'sed-rerum-vitae-qui-ex-placeat-repellat', NULL, 'Earum sed veniam delectus deserunt. Voluptatum debitis veniam omnis. Aliquid et quaerat aut sit voluptatem non. Unde inventore beatae aut magni.', '<p>Illum alias velit iusto ad facere qui ad. Aliquam non eum tempore consequatur. Ut ipsam sed fugiat odio aut voluptas. Ea officia amet maiores corporis quis aut.</p><p>Voluptate sequi quaerat eos. Sapiente neque vitae error sed cumque laboriosam ad. Ut voluptatibus vero facilis est autem beatae illum. Aut quasi enim voluptatem qui.</p><p>Et non incidunt qui aut et. Consequuntur repudiandae doloribus eum corporis et animi doloremque. Distinctio quod voluptatibus amet quidem velit tenetur.</p><p>Saepe voluptatem eos cum officiis blanditiis ut. Quisquam eligendi quis praesentium nostrum est. Nobis perspiciatis et quae error voluptatem.</p><p>Esse ut aspernatur qui ut. Et totam unde aut explicabo non in minus. Sit excepturi nobis quis numquam dolor quo repellat.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(10, 1, 2, 'Sapiente veniam perferendis et recusandae minima qui.', 'reiciendis-ducimus-soluta-tempora-possimus-amet-nemo', NULL, 'Sint ipsam eos id rem modi in illo in. Animi rerum rerum fuga atque dignissimos et. Dolorum est quo reiciendis aut eos aliquam accusantium. Placeat dignissimos doloremque soluta aut nulla dolorum.', '<p>Dolores quaerat et et ea nihil et accusamus. In quia aut laborum labore odit ab eos. Soluta amet rerum non et.</p><p>Ab architecto quis voluptatem nemo. Doloremque delectus reprehenderit at quae. Rerum inventore non quod tempore id esse voluptas. Doloribus rem ipsum dignissimos odio debitis aperiam.</p><p>Saepe eius et omnis in iure qui. Modi esse vel non provident rem doloremque officiis. Facilis mollitia cumque dolor dolores. Tempora aut sapiente quia provident dolore est.</p><p>Ducimus iure dolorem voluptas ut et et occaecati. Voluptate nihil sint delectus quos. Et odit quibusdam ut repudiandae adipisci debitis. Dolorem tempora dolor qui ad quisquam aut ipsum.</p><p>Veniam sed id eaque molestiae porro consequatur accusamus. Tenetur libero cupiditate maiores rerum. Ut officiis fugiat modi exercitationem itaque at. Nihil et eveniet odio qui hic.</p><p>Libero exercitationem nesciunt odit maxime molestiae temporibus optio temporibus. Aut id voluptates quia mollitia et sunt. Voluptas dignissimos eos eos facere et ipsam neque. Quaerat omnis aut sint mollitia.</p><p>Cumque omnis eveniet minima sed iure ipsum. Et dignissimos error atque temporibus. Aliquam excepturi voluptas officiis laudantium iste et quo. Odio unde assumenda perferendis perspiciatis inventore iusto recusandae ea.</p><p>Nobis et ipsam sapiente animi consectetur odit. Autem in et odio quia blanditiis voluptas alias. Dignissimos ipsam voluptates eligendi sunt. Eaque totam provident itaque quo architecto nulla ea.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(11, 2, 2, 'Repellat voluptatum voluptatibus.', 'odit-earum-in-ullam-ut-et-nisi-illum', NULL, 'Nesciunt rem quia et omnis. Ut animi nihil et optio. Quo omnis voluptas minus molestiae.', '<p>Velit et eum et aliquid excepturi. Molestiae non et doloremque cumque est et voluptatem. Molestias sed nihil eveniet quam. Neque repellendus sit autem laborum consequatur.</p><p>Quam libero in ex nisi. Est harum perspiciatis facere sint. Aut voluptatibus et minima omnis quia.</p><p>A possimus minima dolorem nam. Quo exercitationem qui sed perferendis reiciendis. Facilis explicabo exercitationem tenetur voluptas.</p><p>Quos ut voluptas dicta necessitatibus officiis saepe. Ipsum mollitia aut temporibus aperiam unde. Eaque est enim totam. Autem porro id nesciunt reprehenderit facere molestiae illo.</p><p>Repellat eos nobis ipsum veniam. Distinctio vel qui tempore consequatur possimus repellat nihil. Illum eum voluptatem aliquam enim sapiente vero consectetur fugit.</p><p>Vero nisi ea officia ad omnis eum laboriosam. Quidem accusantium et libero dolor odit eum. Alias unde error nam qui quam excepturi rerum velit.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(12, 2, 3, 'Est adipisci repudiandae aut consequatur.', 'saepe-exercitationem-ut-ratione-sint-nisi-totam-qui', NULL, 'Molestias quos quia consectetur et. Voluptatem nam et illum illum necessitatibus. Voluptatem dolorum officia dolor sed. Distinctio harum totam vitae amet harum.', '<p>Fugiat possimus eveniet illum dolor ut sunt. Aut tenetur alias qui quae quae quis amet. Et assumenda in illo voluptate inventore omnis sequi.</p><p>Tempore voluptatem accusantium dolor temporibus voluptatibus. Quidem excepturi ut quo facere nisi cum. Sit voluptatem voluptatum nesciunt sed. Voluptatibus velit dolores nemo consequuntur aut sunt. Esse earum sint error sapiente esse assumenda.</p><p>In soluta modi saepe sit dolor eius iste. Sit molestiae eum sit blanditiis. Corporis et et quaerat voluptate. Labore cum minima repellat earum asperiores qui labore.</p><p>Eaque modi tempore fuga tempora error expedita odit. Est et dolores dignissimos non amet mollitia totam. Voluptate quidem autem nobis repellendus.</p><p>Iure blanditiis ut provident atque. Exercitationem et eaque ratione similique deleniti ut consequatur recusandae. Pariatur excepturi ut occaecati sed nostrum. Perferendis ab ut unde facere.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(13, 2, 3, 'Ut expedita.', 'laboriosam-aut-eos-quod-rerum-laborum-ipsam', NULL, 'Corporis et et iure commodi omnis est. Ut eum omnis asperiores voluptas consequuntur. Fugiat dolorem vel laborum excepturi qui minus a quo.', '<p>Esse exercitationem ex nesciunt impedit excepturi. Voluptatem ea porro voluptates quis odit molestiae tenetur. Vero accusantium aut perferendis voluptas vel reiciendis consequuntur est. Vel eligendi voluptatem et necessitatibus nulla non distinctio.</p><p>Magnam aliquam consequuntur repudiandae quia praesentium enim. Ex quae laborum est maxime.</p><p>Et praesentium repellat dicta dolorem dignissimos culpa. Consequatur aliquam dignissimos neque velit in. Commodi a non voluptatem voluptates.</p><p>Nihil dolore odit non rerum qui quis pariatur delectus. Rem ut sint delectus modi sed libero. Asperiores quae ea amet voluptate sit omnis et.</p><p>Sint amet et culpa dolorem voluptates voluptatem. Sit tempora et nemo a officiis magni porro quibusdam. Repellat rerum aut officia neque suscipit incidunt sapiente. Dolores ex sint iste voluptas voluptatem minima possimus.</p><p>Ea voluptatem eveniet aperiam rem illum sit. Tenetur eligendi et ut sed ad eligendi veritatis. Tenetur et similique et earum eligendi incidunt. Et ut rerum voluptas beatae doloremque impedit voluptate.</p><p>Et est culpa quidem dolore ut excepturi. In error deleniti optio commodi voluptatibus. Porro modi non odio atque accusantium molestiae non. Aut et voluptatem molestias dignissimos corrupti sed.</p><p>Ipsa voluptatum quae sit ratione tempora. Molestias nesciunt est ut vel aspernatur exercitationem. Est qui est facere temporibus. Occaecati excepturi quos tempora odio a adipisci ad amet.</p><p>Quis sed vitae porro facere voluptatem est reiciendis. Nesciunt numquam rerum nostrum quas et.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(14, 2, 3, 'Laborum accusamus pariatur vitae culpa deleniti.', 'repellat-corporis-quis-praesentium-quisquam-voluptatum', NULL, 'Qui aut quos sequi animi ut aperiam blanditiis. Beatae ut animi doloribus alias excepturi ipsam. Quaerat exercitationem dolore ducimus quaerat sed necessitatibus est. Provident facilis fugit earum qui.', '<p>Eos dolores aut quis maiores illum beatae ducimus. Omnis ut mollitia consectetur recusandae ea. Architecto nobis quia sit excepturi blanditiis vel unde sed.</p><p>Nulla eos quasi autem placeat error molestiae. Architecto quo exercitationem ipsa facere molestiae ex ipsa. Quo in quam nam consequatur cumque tenetur velit facere.</p><p>Beatae sed deserunt tempora maxime cum inventore. Ab qui praesentium eos cum doloremque. Tenetur itaque et doloremque quam. Nostrum provident quo fugiat animi.</p><p>Qui totam officia aut reprehenderit et molestiae consequatur. Qui sint ex et consequatur neque et aliquam. Quia laboriosam dolores voluptatem ad dolores. Molestiae aut deleniti qui quisquam temporibus.</p><p>Odit consectetur cumque autem id nam. Officia sunt rem in voluptas iure aut est quo. Nulla rem eos velit molestias in.</p><p>Cum ullam eligendi ut maiores dicta. Iure modi expedita eligendi sit laboriosam ipsa quia rem. Quia sunt illo molestiae.</p><p>A voluptates eligendi at et. Non officia molestias sint occaecati tempora. Laborum enim alias at inventore tempore.</p><p>Necessitatibus nihil deleniti voluptatibus explicabo qui consequatur. Ad culpa sunt voluptas fuga inventore ut et. Dolor et modi aspernatur voluptatum sint velit. Nam esse earum labore dicta voluptas nostrum sequi.</p><p>Similique sit ut veritatis qui quod facilis. Nisi aliquam facere eaque labore. Aut sed voluptatem aut rerum.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(15, 2, 2, 'Rerum neque sed quod quis et modi dolores.', 'molestiae-qui-eveniet-corrupti-quia', NULL, 'Sit unde dignissimos aut voluptatem quis eius. Beatae earum porro tempore consequatur nobis enim. Consequatur molestias id quia nemo.', '<p>Et expedita nulla qui. Error amet quidem iure harum sunt excepturi ducimus.</p><p>Cumque unde eum facilis delectus est et. Quis qui aut aspernatur et id sed magni culpa. Ea illum nemo et unde. Illo qui quas sunt dolorem. Quibusdam nihil suscipit sunt ut.</p><p>Mollitia voluptatibus voluptatem nostrum enim unde laboriosam. Et odit cum qui a perspiciatis. Voluptas occaecati fugiat et tempora ipsam culpa cumque.</p><p>Ea quibusdam vero perspiciatis vel enim deserunt voluptatibus rerum. Nihil soluta et suscipit quia sint. Dicta minima quod debitis dolores dicta autem. Vel perspiciatis et optio sunt illo. Officia dignissimos quisquam minus quas.</p><p>Minima minima est id dicta. Reiciendis reiciendis omnis doloremque. Culpa aut quis qui asperiores ut. Vero mollitia eos minima et cumque porro ut. Et velit nemo animi ducimus neque ea autem.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(16, 3, 3, 'Odio nam ab natus facilis beatae.', 'et-minima-deserunt-est-nisi-nam-possimus', NULL, 'Facilis voluptatem voluptates sit amet. Neque nihil porro id consectetur dolores sequi.', '<p>Ut ut corrupti asperiores illum nam expedita sit dolor. Quisquam et ratione molestias consequatur voluptatibus. Fugiat quo fugiat et commodi non ut. Eius assumenda voluptas earum hic cupiditate.</p><p>Quis modi excepturi veniam odit et dolorum. Culpa soluta autem suscipit atque. Voluptatibus eos autem rerum tempora unde sint qui. Praesentium voluptatibus molestiae dolorum quisquam voluptatem.</p><p>Saepe tenetur perferendis non at cupiditate qui aliquid. Dicta vitae voluptatem fugiat perferendis vel illo ut voluptas. Fugit minus adipisci est nemo at.</p><p>Optio ea reprehenderit ducimus asperiores error rerum. Repellendus quo occaecati exercitationem repellat omnis sunt. Incidunt quae sunt dolor voluptatem sunt minus quidem.</p><p>Omnis consequuntur debitis non accusamus et qui omnis commodi. Et tempora eos et voluptas ut quia omnis. Quia magnam aut consequuntur ullam consequuntur magni. Et voluptatum voluptas ullam aut ipsam dolores aut. Occaecati consequatur qui dignissimos necessitatibus et.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(17, 1, 3, 'Odio saepe laudantium reiciendis ex.', 'tenetur-et-sit-mollitia', NULL, 'Harum ipsam numquam non commodi praesentium tenetur et. Rerum expedita voluptatum modi tempore est et tempore dolorem. Numquam ex est magni optio aut. Qui ipsum quaerat dolorem perferendis.', '<p>Ipsum saepe dolorem doloribus veritatis veritatis. Iusto incidunt placeat et dolore natus voluptate perspiciatis. Eius quia id fugit. Totam asperiores sed explicabo possimus.</p><p>Quo consequatur distinctio quaerat libero illo provident eveniet qui. Vitae facilis odio sit est quia molestiae. Ea et consequatur illo maiores dignissimos eaque. Totam recusandae occaecati nobis dolorem vel ut.</p><p>Ut numquam sit aut consequatur iure porro sit. Vero quasi occaecati id dolores harum voluptatem dolor. Delectus quisquam necessitatibus ut.</p><p>Quibusdam perspiciatis rem iste sit et impedit laborum. Et porro exercitationem hic ducimus. Nulla eum velit est accusamus maiores.</p><p>Ut qui sed deserunt saepe non. Vero nesciunt iste ut quibusdam dolorem ducimus enim. Nobis quod porro iste saepe corporis nobis doloremque.</p><p>Ut dolor magnam cumque fugit omnis. Incidunt accusamus beatae facilis omnis ut. Eos sequi delectus aut non. Voluptas architecto dolor et est quia aut.</p><p>Ipsam voluptatem optio aut nemo. Modi occaecati blanditiis veritatis sint molestiae ea explicabo non. Tenetur voluptatum assumenda natus est maxime. Velit voluptatem fugiat consequatur corporis nostrum blanditiis. Pariatur a nulla sit.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(18, 3, 3, 'Cupiditate voluptatibus similique sed nihil amet dolore hic sit.', 'velit-officiis-reiciendis-non-in-ea-sed', NULL, 'Repellat sed perferendis omnis a dolores ea nisi. Sit id ea quia facere optio dolor placeat. Voluptatem cupiditate in et atque ad enim maxime asperiores. Nihil inventore molestiae provident ad cum dolorem culpa. Commodi molestiae quo aspernatur eum.', '<p>Assumenda culpa eius animi ut nihil facere. In corporis repudiandae reprehenderit facilis et accusamus impedit aut. Impedit esse at autem cumque modi iusto sint. Voluptas et magnam eligendi omnis.</p><p>Consequuntur ab deserunt voluptatem sequi commodi aspernatur. Doloremque soluta magnam qui. Et est ut aliquid dolor eveniet laboriosam id. Quia necessitatibus ut adipisci alias non odit.</p><p>Voluptas velit laborum quasi qui quo harum. Ea ut itaque omnis qui ut. Nihil praesentium id quis itaque officia. Nesciunt animi ut voluptates recusandae.</p><p>Consequatur eaque omnis magni nisi architecto quod. Qui sunt magni enim tempora expedita. Quod quia et qui doloremque reiciendis. Veniam ratione veritatis omnis dolores sunt.</p><p>Perferendis totam nisi laborum et est. Quos animi vitae possimus quae qui architecto est. Aut voluptatem voluptates mollitia optio laudantium non laborum.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(19, 3, 2, 'Qui autem.', 'possimus-ex-illo-nulla-dolores-optio-aliquid-cupiditate', NULL, 'Sit vel magni vel numquam. Necessitatibus et itaque fugit unde placeat qui velit ut. Tempore quae id eos alias hic perferendis in. Et et accusamus explicabo.', '<p>Reiciendis architecto saepe inventore sequi fugiat dolor non voluptates. Libero quod deleniti aspernatur aut illo sint. Doloremque consequatur sunt voluptas iure adipisci. Ea et molestias ipsa.</p><p>Quae qui quis id quaerat. Quis dolor asperiores aut debitis necessitatibus. Ea recusandae in nostrum eum.</p><p>Consequatur saepe exercitationem blanditiis non. Aut ea ut harum et. Quo velit quas maxime necessitatibus cum mollitia. Quas quia distinctio enim cupiditate rerum.</p><p>Recusandae sed explicabo corrupti aut officiis quibusdam reiciendis magnam. Sed et voluptas est ut quo. Ab qui iste soluta error. Rerum praesentium dignissimos expedita quisquam vel.</p><p>Ad exercitationem aut architecto aliquam. Quia dicta aliquid dolore facere explicabo corrupti. Recusandae tenetur rerum eaque cum dicta ut labore.</p><p>Vel qui sit saepe. Dolor eligendi culpa accusantium molestiae. Adipisci ducimus quae laboriosam similique rerum earum. Sit explicabo ut rerum in culpa excepturi aut. Et quisquam beatae exercitationem qui magni dolor molestias.</p><p>Consequuntur nobis nihil quisquam sapiente. Et maiores facere quisquam officiis laboriosam ad dolorum. Eum ad eius fugit nihil molestias. Mollitia officia at doloremque odio ut inventore.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(20, 1, 3, 'Nobis iusto in.', 'occaecati-minima-aliquid-tempora-aut-molestiae-aut-doloribus', NULL, 'Suscipit est omnis aut. Fuga fugit cum perspiciatis sed hic facere. Aut et ad ea corrupti saepe similique.', '<p>Velit rem consequatur quia quo quo officia deserunt alias. Voluptates neque et excepturi adipisci. Dolorem placeat porro voluptas et atque deleniti.</p><p>Aliquid odit explicabo tempora est adipisci veniam. Sunt rem ab autem illum magni est. Expedita beatae ipsum culpa animi voluptatem deleniti delectus.</p><p>Molestiae veniam et doloremque sed voluptatem praesentium. Molestias magnam mollitia reprehenderit ducimus dolor. Nesciunt voluptas enim quo quisquam totam in quaerat debitis. Earum minima et voluptate impedit aut saepe voluptatem.</p><p>Natus deserunt quasi in ea officiis. Neque aut ipsa aut vel velit possimus omnis.</p><p>Dolorem doloribus tempora quis molestiae consequuntur excepturi ratione. Qui et a accusamus dolor sunt. Provident veritatis aut et. Qui optio ut deserunt qui minus.</p><p>Debitis ut consequatur nesciunt reiciendis doloremque. Nam et odio iure natus quibusdam quas tenetur magnam. Earum velit qui architecto doloribus. Veniam sit explicabo tempore deserunt culpa.</p>', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(21, 1, 1, 'Tips NNN', 'tips-nnn', 'post-images/5Qez8tkE2KTDa9EpBiVklMLr1LnKlFO27VT23vkn.png', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, dolore quis nemo iure qui consequuntur ea. Eaque, dignissimos nisi quod laborum eos illo id temporibus numquam, ea dolorem perspiciatis!...', '<div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, dolore quis nemo iure qui consequuntur ea. Eaque, dignissimos nisi quod laborum eos illo id temporibus numquam, ea dolorem perspiciatis! Sequi sit debitis, voluptatibus, hic earum tempore libero fugiat excepturi dolor, incidunt voluptate porro? Illum provident corporis voluptate maiores pariatur eligendi quam nobis aliquid omnis, dolore nesciunt fuga eum, adipisci sint aliquam repellendus cumque temporibus alias iure. Ducimus quas molestiae doloremque fugit, corporis amet provident iste soluta consectetur est dolorum odio tempora, possimus in ullam omnis vel nam cumque rem. Ullam molestias dolores sit? Veniam inventore repudiandae ut recusandae eum voluptates!<br><br><strong>Berikut tips NNN yang bisa kamu lakukan</strong></div><ol><li>Engga ada tips apa-apa</li></ol><div><strong>Terimakasih</strong></div>', NULL, '2021-10-30 04:27:58', '2021-10-30 08:40:19'),
	(22, 3, 1, 'Membuat Playlist yang Semua Orang Suka', 'asede-penis-sama-lu-semua', 'post-images/pC8SOcwYfIvtmKY97Xh221qMhaAtC6A21CVMAzAo.jpg', 'asede penis sama lu semua, ngesex ngesex sama lu semua', '<div>asede penis sama lu semua, ngesex ngesex sama lu semua</div>', NULL, '2021-10-30 04:40:52', '2021-12-06 09:35:07'),
	(23, 1, 1, 'Cara Menjadi Music Director Handal', 'cara-menjadi-music-director-handal', 'post-images/ZaiidZdWi64q2GTB2s3S7s1fVCYicVqOgZzjV9dz.jpg', 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sequi, blanditiis velit! Reiciendis placeat provident tempore beatae asperiores facere quo mollitia ab pariatur voluptatem nesciunt vero, dolo...', '<div>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sequi, blanditiis velit! Reiciendis placeat provident tempore beatae asperiores facere quo mollitia ab pariatur voluptatem nesciunt vero, dolor tempora nulla ratione saepe, quos laudantium deserunt. Delectus hic natus, necessitatibus, autem id fugit eligendi porro ex beatae aliquam possimus laboriosam facilis fuga pariatur tempore amet deserunt voluptatem quibusdam ducimus accusantium ea impedit eos atque. Tenetur, necessitatibus. Vero fugit libero porro cum voluptatum quis sunt? Tenetur totam quas odit assumenda eligendi in saepe optio ad impedit. Ab quasi provident facere ullam enim maxime numquam! Inventore amet ipsa obcaecati, velit porro dolorem vel rem quia.<br><br><strong>TERTIPU KAMU BANGSAT</strong></div>', NULL, '2021-10-30 04:47:44', '2021-12-06 09:36:30');
/*!40000 ALTER TABLE `posts` ENABLE KEYS */;

-- membuang struktur untuk table arsa_blog.users
CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `username` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_username_unique` (`username`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Membuang data untuk tabel arsa_blog.users: ~4 rows (lebih kurang)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `name`, `username`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES
	(1, 'Hadi Akbar', 'Byksue', 'harusapaan@gmail.com', NULL, '$2y$10$8KpT26q6dCGE5L3alw.1DObpp/zChGNowrV5WeuMt8tGrvDCTQPPq', NULL, '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(2, 'Rudi Gunawan', 'kanda84', 'novi.pradipta@example.net', '2021-10-30 04:26:24', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '6JvOh5l69hKfMDkXhnRZ70jaxlbB2u3SjAmADVxeeejkwNzCvEatVK1LKLoa', '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(3, 'Malik Hutagalung', 'kania.laksmiwati', 'prabowo05@example.com', '2021-10-30 04:26:24', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '9rhK9G47RNNW1AnUvEyag3VfZEJErC5lSggL8sM4Bb9NYOvEAuyC9tEWfGXm', '2021-10-30 04:26:24', '2021-10-30 04:26:24'),
	(4, 'Queen Lestari', 'dewi.adriansyah', 'rnurdiyanti@example.net', '2021-10-30 04:26:24', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '8etoVIk6lq', '2021-10-30 04:26:24', '2021-10-30 04:26:24');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
